AnimationPointers:
	table_width 2, AnimationPointers

	dw EkansAnimation
	dw ArbokAnimation
	dw BaltoyAnimation
	dw ClaydolAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw RattataAnimation
	dw RaticateAnimation
	dw BidoofAnimation
	dw BibarelAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw DunsparceAnimation
	dw DudnsparceAnimation
	dw StantlerAnimation
	dw WyrdeerAnimation
	dw DittoAnimation
	dw SmeargleAnimation
	dw BunearyAnimation
	dw LopunnyAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw GirafarigAnimation
	dw FarigirafAnimation
	dw PorygonAnimation
	dw Porygon2Animation
	dw PorygonzAnimation
	dw HappinyAnimation
	dw ChanseyAnimation
	dw BlisseyAnimation
	dw KecleonAnimation
	dw MunchlaxAnimation
	dw SnorlaxAnimation
	dw FletchlingAnimation
	dw FletchindrAnimation
	dw TalonflameAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw CrobatAnimation
	dw SkarmoryAnimation
	dw MurkrowAnimation
	dw HonchkrowAnimation
	dw CaterpieAnimation
	dw MetapodAnimation
	dw ButterfreeAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw ParasAnimation
	dw ParasectAnimation
	dw VenonatAnimation
	dw VenomothAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw SurskitAnimation
	dw MasquerainAnimation
	dw ShuckleAnimation
	dw ScytherAnimation
	dw ScizorAnimation
	dw KleavorAnimation
	dw HeracrossAnimation
	dw PinsirAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw CorphishAnimation
	dw CrawdauntAnimation
	dw BuizelAnimation
	dw FloatzelAnimation
	dw KrabbyAnimation
	dw KinglerAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw PoliwagAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw PolitoedAnimation
	dw GoldeenAnimation
	dw SeakingAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw QwilfishAnimation
	dw CorsolaAnimation
	dw FeebasAnimation
	dw MiloticAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw KingdraAnimation
	dw CarvanhaAnimation
	dw SharpedoAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw MudkipAnimation
	dw MarshtompAnimation
	dw SwampertAnimation
	dw NumelAnimation
	dw CameruptAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw LarvestaAnimation
	dw VolcoronaAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw TorkoalAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TorchicAnimation
	dw CombuskenAnimation
	dw BlazikenAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw LotadAnimation
	dw LombreAnimation
	dw LudicoloAnimation
	dw ApplinAnimation
	dw FlappleAnimation
	dw AppletunAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw CottoneeAnimation
	dw WhimsicottAnimation
	dw MaractusAnimation
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw TreekoAnimation
	dw GrovyleAnimation
	dw SceptileAnimation
	dw PichuAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw ShinxAnimation
	dw LuxioAnimation
	dw LuxrayAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw MagnezoneAnimation
	dw ElectrikeAnimation
	dw ManectricAnimation
	dw PawmiAnimation
	dw PawmoAnimation
	dw PawmotAnimation
	dw MachopAnimation
	dw MachokeAnimation
	dw MachampAnimation
	dw TyrogueAnimation
	dw HitmonleeAnimation
	dw HitmonchanAnimation
	dw HitmontopAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw CroagunkAnimation
	dw ToxicroakAnimation
	dw PanchamAnimation
	dw PangoroAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw RockruffAnimation
	dw Lycanroc1Animation
	dw Lycanroc2Animation
	dw Lycanroc3Animation
	dw BonslyAnimation
	dw SudowoodoAnimation
	dw OddishAnimation
	dw GloomAnimation
	dw VileplumeAnimation
	dw BellossomAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw RhyperiorAnimation
	dw LunatoneAnimation
	dw SolrockAnimation
	dw AnorithAnimation
	dw ArmaldoAnimation
	dw LileepAnimation
	dw CradillyAnimation
	dw TirtougaAnimation
	dw CaracostaAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw DiglettAnimation
	dw DugtrioAnimation
	dw OnixAnimation
	dw SteelixAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw WooperAnimation
	dw ClodsireAnimation
	dw GligarAnimation
	dw GliscorAnimation
	dw TrapinchAnimation
	dw VibravaAnimation
	dw FlygonAnimation
	dw VuplixAnimation
	dw NinetalesAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw MamoswineAnimation
	dw ShellderAnimation
	dw CloysterAnimation
	dw SnoruntAnimation
	dw GlalieAnimation
	dw FroslassAnimation
	dw CubchooAnimation
	dw BearticAnimation
	dw LaprasAnimation
	dw SnomAnimation
	dw FrosmothAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw UnownAnimation
	dw DrowzeeAnimation
	dw HypnoAnimation
	dw WynautAnimation
	dw WobbuffetAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw SlowkingAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw SneaselAnimation
	dw WeavileAnimation
	dw AbsolAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw DrifloonAnimation
	dw DrifblimAnimation
	dw MisdreavusAnimation
	dw MismagiusAnimation
	dw DuskullAnimation
	dw DusclopsAnimation
	dw DusknoirAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw RotomAnimation
	dw SpiritombAnimation
	dw Nidoran_mAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw Nidoran_fAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw GulpinAnimation
	dw SwalotAnimation
	dw StunkyAnimation
	dw SkuntankAnimation
	dw SkrelpAnimation
	dw DragalgeAnimation
	dw AronAnimation
	dw LaironAnimation
	dw AggronAnimation
	dw MawileAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw AzurillAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw TogekissAnimation
	dw CleffaAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw MimikyuAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw DrampaAnimation
	dw TurtonatorAnimation
	dw BagonAnimation
	dw ShelgonAnimation
	dw SalamenceAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw BeldumAnimation
	dw MetangAnimation
	dw MetagrossAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw GlaceonAnimation
	dw LeafeonAnimation
	dw SylveonAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw RegiceAnimation
	dw RegirockAnimation
	dw RegisteelAnimation
	dw HeatranAnimation
	dw ManaphyAnimation
	dw JirachiAnimation
	dw CelebiAnimation
	dw DeoxysAnimation
	dw MewAnimation

	assert_table_length NUM_POKEMON
