BitmasksPointers:
	table_width 2, BitmasksPointers

	dw EkansBitmasks
	dw ArbokBitmasks
	dw BaltoyBitmasks
	dw ClaydolBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw BidoofBitmasks
	dw BibarelBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw DunsparceBitmasks
	dw DudnsparceBitmasks
	dw StantlerBitmasks
	dw WyrdeerBitmasks
	dw DittoBitmasks
	dw SmeargleBitmasks
	dw BunearyBitmasks
	dw LopunnyBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw GirafarigBitmasks
	dw FarigirafBitmasks
	dw PorygonBitmasks
	dw Porygon2Bitmasks
	dw PorygonzBitmasks
	dw HappinyBitmasks
	dw ChanseyBitmasks
	dw BlisseyBitmasks
	dw KecleonBitmasks
	dw MunchlaxBitmasks
	dw SnorlaxBitmasks
	dw FletchlingBitmasks
	dw FletchindrBitmasks
	dw TalonflameBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw CrobatBitmasks
	dw SkarmoryBitmasks
	dw MurkrowBitmasks
	dw HonchkrowBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw SurskitBitmasks
	dw MasquerainBitmasks
	dw ShuckleBitmasks
	dw ScytherBitmasks
	dw ScizorBitmasks
	dw KleavorBitmasks
	dw HeracrossBitmasks
	dw PinsirBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw CorphishBitmasks
	dw CrawdauntBitmasks
	dw BuizelBitmasks
	dw FloatzelBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw PolitoedBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw QwilfishBitmasks
	dw CorsolaBitmasks
	dw FeebasBitmasks
	dw MiloticBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw KingdraBitmasks
	dw CarvanhaBitmasks
	dw SharpedoBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw MudkipBitmasks
	dw MarshtompBitmasks
	dw SwampertBitmasks
	dw NumelBitmasks
	dw CameruptBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw LarvestaBitmasks
	dw VolcoronaBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw TorkoalBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TorchicBitmasks
	dw CombuskenBitmasks
	dw BlazikenBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw LotadBitmasks
	dw LombreBitmasks
	dw LudicoloBitmasks
	dw ApplinBitmasks
	dw FlappleBitmasks
	dw AppletunBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CottoneeBitmasks
	dw WhimsicottBitmasks
	dw MaractusBitmasks
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw TreekoBitmasks
	dw GrovyleBitmasks
	dw SceptileBitmasks
	dw PichuBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw ShinxBitmasks
	dw LuxioBitmasks
	dw LuxrayBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw ElectrikeBitmasks
	dw ManectricBitmasks
	dw PawmiBitmasks
	dw PawmoBitmasks
	dw PawmotBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw TyrogueBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw HitmontopBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw PanchamBitmasks
	dw PangoroBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw RockruffBitmasks
	dw Lycanroc1Bitmasks
	dw Lycanroc2Bitmasks
	dw Lycanroc3Bitmasks
	dw BonslyBitmasks
	dw SudowoodoBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw BellossomBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw RhyperiorBitmasks
	dw LunatoneBitmasks
	dw SolrockBitmasks
	dw AnorithBitmasks
	dw ArmaldoBitmasks
	dw LileepBitmasks
	dw CradillyBitmasks
	dw TirtougaBitmasks
	dw CaracostaBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw OnixBitmasks
	dw SteelixBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw WooperBitmasks
	dw ClodsireBitmasks
	dw GligarBitmasks
	dw GliscorBitmasks
	dw TrapinchBitmasks
	dw VibravaBitmasks
	dw FlygonBitmasks
	dw VuplixBitmasks
	dw NinetalesBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw SnoruntBitmasks
	dw GlalieBitmasks
	dw FroslassBitmasks
	dw CubchooBitmasks
	dw BearticBitmasks
	dw LaprasBitmasks
	dw SnomBitmasks
	dw FrosmothBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw UnownBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw WynautBitmasks
	dw WobbuffetBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw SlowkingBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw SneaselBitmasks
	dw WeavileBitmasks
	dw AbsolBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw DrifloonBitmasks
	dw DrifblimBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw DusknoirBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw RotomBitmasks
	dw SpiritombBitmasks
	dw Nidoran_mBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw Nidoran_fBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw GulpinBitmasks
	dw SwalotBitmasks
	dw StunkyBitmasks
	dw SkuntankBitmasks
	dw SkrelpBitmasks
	dw DragalgeBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw MawileBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw AzurillBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw TogekissBitmasks
	dw CleffaBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw MimikyuBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw DrampaBitmasks
	dw TurtonatorBitmasks
	dw BagonBitmasks
	dw ShelgonBitmasks
	dw SalamenceBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw BeldumBitmasks
	dw MetangBitmasks
	dw MetagrossBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw GlaceonBitmasks
	dw LeafeonBitmasks
	dw SylveonBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw RegiceBitmasks
	dw RegirockBitmasks
	dw RegisteelBitmasks
	dw HeatranBitmasks
	dw ManaphyBitmasks
	dw JirachiBitmasks
	dw CelebiBitmasks
	dw DeoxysBitmasks
	dw MewBitmasks
	assert_table_length NUM_POKEMON
