FramesPointers:
	table_width 3, FramesPointers

	dba EkansFrames
	dba ArbokFrames
	dba BaltoyFrames
	dba ClaydolFrames
	dba YanmaFrames
	dba YanmegaFrames
	dba RattataFrames
	dba RaticateFrames
	dba BidoofFrames
	dba BibarelFrames
	dba SentretFrames
	dba FurretFrames
	dba DunsparceFrames
	dba DudnsparceFrames
	dba StantlerFrames
	dba WyrdeerFrames
	dba DittoFrames
	dba SmeargleFrames
	dba BunearyFrames
	dba LopunnyFrames
	dba MeowthFrames
	dba PersianFrames
	dba GirafarigFrames
	dba FarigirafFrames
	dba PorygonFrames
	dba Porygon2Frames
	dba PorygonzFrames
	dba HappinyFrames
	dba ChanseyFrames
	dba BlisseyFrames
	dba KecleonFrames
	dba MunchlaxFrames
	dba SnorlaxFrames
	dba FletchlingFrames
	dba FletchindrFrames
	dba TalonflameFrames
	dba HoothootFrames
	dba NoctowlFrames
	dba PidgeyFrames
	dba PidgeottoFrames
	dba PidgeotFrames
	dba ZubatFrames
	dba GolbatFrames
	dba CrobatFrames
	dba SkarmoryFrames
	dba MurkrowFrames
	dba HonchkrowFrames
	dba CaterpieFrames
	dba MetapodFrames
	dba ButterfreeFrames
	dba SpinarakFrames
	dba AriadosFrames
	dba ParasFrames
	dba ParasectFrames
	dba VenonatFrames
	dba VenomothFrames
	dba PinecoFrames
	dba ForretressFrames
	dba SurskitFrames
	dba MasquerainFrames
	dba ShuckleFrames
	dba ScytherFrames
	dba ScizorFrames
	dba KleavorFrames
	dba HeracrossFrames
	dba PinsirFrames
	dba MagikarpFrames
	dba GyaradosFrames
	dba CorphishFrames
	dba CrawdauntFrames
	dba BuizelFrames
	dba FloatzelFrames
	dba KrabbyFrames
	dba KinglerFrames
	dba StaryuFrames
	dba StarmieFrames
	dba PoliwagFrames
	dba PoliwhirlFrames
	dba PoliwrathFrames
	dba PolitoedFrames
	dba GoldeenFrames
	dba SeakingFrames
	dba RemoraidFrames
	dba OctilleryFrames
	dba QwilfishFrames
	dba CorsolaFrames
	dba FeebasFrames
	dba MiloticFrames
	dba ChinchouFrames
	dba LanturnFrames
	dba HorseaFrames
	dba SeadraFrames
	dba KingdraFrames
	dba CarvanhaFrames
	dba SharpedoFrames
	dba SquirtleFrames
	dba WartortleFrames
	dba BlastoiseFrames
	dba TotodileFrames
	dba CroconawFrames
	dba FeraligatrFrames
	dba MudkipFrames
	dba MarshtompFrames
	dba SwampertFrames
	dba NumelFrames
	dba CameruptFrames
	dba GrowlitheFrames
	dba ArcanineFrames
	dba LarvestaFrames
	dba VolcoronaFrames
	dba PonytaFrames
	dba RapidashFrames
	dba TorkoalFrames
	dba CharmanderFrames
	dba CharmeleonFrames
	dba CharizardFrames
	dba CyndaquilFrames
	dba QuilavaFrames
	dba TyphlosionFrames
	dba TorchicFrames
	dba CombuskenFrames
	dba BlazikenFrames
	dba HoppipFrames
	dba SkiploomFrames
	dba JumpluffFrames
	dba LotadFrames
	dba LombreFrames
	dba LudicoloFrames
	dba ApplinFrames
	dba FlappleFrames
	dba AppletunFrames
	dba ShroomishFrames
	dba BreloomFrames
	dba SunkernFrames
	dba SunfloraFrames
	dba BellsproutFrames
	dba WeepinbellFrames
	dba VictreebelFrames
	dba ExeggcuteFrames
	dba ExeggutorFrames
	dba CottoneeFrames
	dba WhimsicottFrames
	dba MaractusFrames
	dba BulbasaurFrames
	dba IvysaurFrames
	dba VenusaurFrames
	dba ChikoritaFrames
	dba BayleefFrames
	dba MeganiumFrames
	dba TreekoFrames
	dba GrovyleFrames
	dba SceptileFrames
	dba PichuFrames
	dba PikachuFrames
	dba RaichuFrames
	dba ShinxFrames
	dba LuxioFrames
	dba LuxrayFrames
	dba MareepFrames
	dba FlaaffyFrames
	dba AmpharosFrames
	dba MagnemiteFrames
	dba MagnetonFrames
	dba MagnezoneFrames
	dba ElectrikeFrames
	dba ManectricFrames
	dba PawmiFrames
	dba PawmoFrames
	dba PawmotFrames
	dba MachopFrames
	dba MachokeFrames
	dba MachampFrames
	dba TyrogueFrames
	dba HitmonleeFrames
	dba HitmonchanFrames
	dba HitmontopFrames
	dba RioluFrames
	dba LucarioFrames
	dba CroagunkFrames
	dba ToxicroakFrames
	dba PanchamFrames
	dba PangoroFrames
	dba GeodudeFrames
	dba GravelerFrames
	dba GolemFrames
	dba RockruffFrames
	dba Lycanroc1Frames
	dba Lycanroc2Frames
	dba Lycanroc3Frames
	dba BonslyFrames
	dba SudowoodoFrames
	dba OddishFrames
	dba GloomFrames
	dba VileplumeFrames
	dba BellossomFrames
	dba RhyhornFrames
	dba RhydonFrames
	dba RhyperiorFrames
	dba LunatoneFrames
	dba SolrockFrames
	dba AnorithFrames
	dba ArmaldoFrames
	dba LileepFrames
	dba CradillyFrames
	dba TirtougaFrames
	dba CaracostaFrames
	dba CuboneFrames
	dba MarowakFrames
	dba DiglettFrames
	dba DugtrioFrames
	dba OnixFrames
	dba SteelixFrames
	dba PhanpyFrames
	dba DonphanFrames
	dba WooperFrames
	dba ClodsireFrames
	dba GligarFrames
	dba GliscorFrames
	dba TrapinchFrames
	dba VibravaFrames
	dba FlygonFrames
	dba VuplixFrames
	dba NinetalesFrames
	dba SwinubFrames
	dba PiloswineFrames
	dba MamoswineFrames
	dba ShellderFrames
	dba CloysterFrames
	dba SnoruntFrames
	dba GlalieFrames
	dba FroslassFrames
	dba CubchooFrames
	dba BearticFrames
	dba LaprasFrames
	dba SnomFrames
	dba FrosmothFrames
	dba AbraFrames
	dba KadabraFrames
	dba AlakazamFrames
	dba UnownFrames
	dba DrowzeeFrames
	dba HypnoFrames
	dba WynautFrames
	dba WobbuffetFrames
	dba SlowpokeFrames
	dba SlowbroFrames
	dba SlowkingFrames
	dba NatuFrames
	dba XatuFrames
	dba HoundourFrames
	dba HoundoomFrames
	dba SneaselFrames
	dba WeavileFrames
	dba AbsolFrames
	dba GastlyFrames
	dba HaunterFrames
	dba GengarFrames
	dba DrifloonFrames
	dba DrifblimFrames
	dba MisdreavusFrames
	dba MismagiusFrames
	dba DuskullFrames
	dba DusclopsFrames
	dba DusknoirFrames
	dba LitwickFrames
	dba LampentFrames
	dba ChandelureFrames
	dba RotomFrames
	dba SpiritombFrames
	dba Nidoran_mFrames
	dba NidorinoFrames
	dba NidokingFrames
	dba Nidoran_fFrames
	dba NidorinaFrames
	dba NidoqueenFrames
	dba KoffingFrames
	dba WeezingFrames
	dba GulpinFrames
	dba SwalotFrames
	dba StunkyFrames
	dba SkuntankFrames
	dba SkrelpFrames
	dba DragalgeFrames
	dba AronFrames
	dba LaironFrames
	dba AggronFrames
	dba MawileFrames
	dba SnubbullFrames
	dba GranbullFrames
	dba AzurillFrames
	dba MarillFrames
	dba AzumarillFrames
	dba TogepiFrames
	dba TogeticFrames
	dba TogekissFrames
	dba CleffaFrames
	dba ClefairyFrames
	dba ClefableFrames
	dba MimikyuFrames
	dba SwabluFrames
	dba AltariaFrames
	dba DrampaFrames
	dba TurtonatorFrames
	dba BagonFrames
	dba ShelgonFrames
	dba SalamenceFrames
	dba DratiniFrames
	dba DragonairFrames
	dba DragoniteFrames
	dba LarvitarFrames
	dba PupitarFrames
	dba TyranitarFrames
	dba BeldumFrames
	dba MetangFrames
	dba MetagrossFrames
	dba EeveeFrames
	dba VaporeonFrames
	dba JolteonFrames
	dba FlareonFrames
	dba EspeonFrames
	dba UmbreonFrames
	dba GlaceonFrames
	dba LeafeonFrames
	dba SylveonFrames
	dba ArticunoFrames
	dba ZapdosFrames
	dba MoltresFrames
	dba RegiceFrames
	dba RegirockFrames
	dba RegisteelFrames
	dba HeatranFrames
	dba ManaphyFrames
	dba JirachiFrames
	dba CelebiFrames
	dba DeoxysFrames
	dba MewFrames
	assert_table_length NUM_POKEMON
