AnimationIdlePointers:
	table_width 2, AnimationIdlePointers
	dw EkansAnimationIdle
	dw ArbokAnimationIdle
	dw BaltoyAnimationIdle
	dw ClaydolAnimationIdle
	dw YanmaAnimationIdle
	dw YanmegaAnimationIdle
	dw RattataAnimationIdle
	dw RaticateAnimationIdle
	dw BidoofAnimationIdle
	dw BibarelAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw DunsparceAnimationIdle
	dw DudnsparceAnimationIdle
	dw StantlerAnimationIdle
	dw WyrdeerAnimationIdle
	dw DittoAnimationIdle
	dw SmeargleAnimationIdle
	dw BunearyAnimationIdle
	dw LopunnyAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw GirafarigAnimationIdle
	dw FarigirafAnimationIdle
	dw PorygonAnimationIdle
	dw Porygon2AnimationIdle
	dw PorygonzAnimationIdle
	dw HappinyAnimationIdle
	dw ChanseyAnimationIdle
	dw BlisseyAnimationIdle
	dw KecleonAnimationIdle
	dw MunchlaxAnimationIdle
	dw SnorlaxAnimationIdle
	dw FletchlingAnimationIdle
	dw FletchindrAnimationIdle
	dw TalonflameAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw PidgeyAnimationIdle
	dw PidgeottoAnimationIdle
	dw PidgeotAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw CrobatAnimationIdle
	dw SkarmoryAnimationIdle
	dw MurkrowAnimationIdle
	dw HonchkrowAnimationIdle
	dw CaterpieAnimationIdle
	dw MetapodAnimationIdle
	dw ButterfreeAnimationIdle
	dw SpinarakAnimationIdle
	dw AriadosAnimationIdle
	dw ParasAnimationIdle
	dw ParasectAnimationIdle
	dw VenonatAnimationIdle
	dw VenomothAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw SurskitAnimationIdle
	dw MasquerainAnimationIdle
	dw ShuckleAnimationIdle
	dw ScytherAnimationIdle
	dw ScizorAnimationIdle
	dw KleavorAnimationIdle
	dw HeracrossAnimationIdle
	dw PinsirAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw CorphishAnimationIdle
	dw CrawdauntAnimationIdle
	dw BuizelAnimationIdle
	dw FloatzelAnimationIdle
	dw KrabbyAnimationIdle
	dw KinglerAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw PolitoedAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw QwilfishAnimationIdle
	dw CorsolaAnimationIdle
	dw FeebasAnimationIdle
	dw MiloticAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw KingdraAnimationIdle
	dw CarvanhaAnimationIdle
	dw SharpedoAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw MudkipAnimationIdle
	dw MarshtompAnimationIdle
	dw SwampertAnimationIdle
	dw NumelAnimationIdle
	dw CameruptAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw LarvestaAnimationIdle
	dw VolcoronaAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw TorkoalAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TorchicAnimationIdle
	dw CombuskenAnimationIdle
	dw BlazikenAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw LotadAnimationIdle
	dw LombreAnimationIdle
	dw LudicoloAnimationIdle
	dw ApplinAnimationIdle
	dw FlappleAnimationIdle
	dw AppletunAnimationIdle
	dw ShroomishAnimationIdle
	dw BreloomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CottoneeAnimationIdle
	dw WhimsicottAnimationIdle
	dw MaractusAnimationIdle
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw TreekoAnimationIdle
	dw GrovyleAnimationIdle
	dw SceptileAnimationIdle
	dw PichuAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw ShinxAnimationIdle
	dw LuxioAnimationIdle
	dw LuxrayAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw MagnezoneAnimationIdle
	dw ElectrikeAnimationIdle
	dw ManectricAnimationIdle
	dw PawmiAnimationIdle
	dw PawmoAnimationIdle
	dw PawmotAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw TyrogueAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw HitmontopAnimationIdle
	dw RioluAnimationIdle
	dw LucarioAnimationIdle
	dw CroagunkAnimationIdle
	dw ToxicroakAnimationIdle
	dw PanchamAnimationIdle
	dw PangoroAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw RockruffAnimationIdle
	dw Lycanroc1AnimationIdle
	dw Lycanroc2AnimationIdle
	dw Lycanroc3AnimationIdle
	dw BonslyAnimationIdle
	dw SudowoodoAnimationIdle
	dw OddishAnimationIdle
	dw GloomAnimationIdle
	dw VileplumeAnimationIdle
	dw BellossomAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw RhyperiorAnimationIdle
	dw LunatoneAnimationIdle
	dw SolrockAnimationIdle
	dw AnorithAnimationIdle
	dw ArmaldoAnimationIdle
	dw LileepAnimationIdle
	dw CradillyAnimationIdle
	dw TirtougaAnimationIdle
	dw CaracostaAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw DiglettAnimationIdle
	dw DugtrioAnimationIdle
	dw OnixAnimationIdle
	dw SteelixAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw WooperAnimationIdle
	dw ClodsireAnimationIdle
	dw GligarAnimationIdle
	dw GliscorAnimationIdle
	dw TrapinchAnimationIdle
	dw VibravaAnimationIdle
	dw FlygonAnimationIdle
	dw VuplixAnimationIdle
	dw NinetalesAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw MamoswineAnimationIdle
	dw ShellderAnimationIdle
	dw CloysterAnimationIdle
	dw SnoruntAnimationIdle
	dw GlalieAnimationIdle
	dw FroslassAnimationIdle
	dw CubchooAnimationIdle
	dw BearticAnimationIdle
	dw LaprasAnimationIdle
	dw SnomAnimationIdle
	dw FrosmothAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw UnownAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw WynautAnimationIdle
	dw WobbuffetAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw SlowkingAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw SneaselAnimationIdle
	dw WeavileAnimationIdle
	dw AbsolAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw DrifloonAnimationIdle
	dw DrifblimAnimationIdle
	dw MisdreavusAnimationIdle
	dw MismagiusAnimationIdle
	dw DuskullAnimationIdle
	dw DusclopsAnimationIdle
	dw DusknoirAnimationIdle
	dw LitwickAnimationIdle
	dw LampentAnimationIdle
	dw ChandelureAnimationIdle
	dw RotomAnimationIdle
	dw SpiritombAnimationIdle
	dw Nidoran_mAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw Nidoran_fAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw GulpinAnimationIdle
	dw SwalotAnimationIdle
	dw StunkyAnimationIdle
	dw SkuntankAnimationIdle
	dw SkrelpAnimationIdle
	dw DragalgeAnimationIdle
	dw AronAnimationIdle
	dw LaironAnimationIdle
	dw AggronAnimationIdle
	dw MawileAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw AzurillAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw TogekissAnimationIdle
	dw CleffaAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw MimikyuAnimationIdle
	dw SwabluAnimationIdle
	dw AltariaAnimationIdle
	dw DrampaAnimationIdle
	dw TurtonatorAnimationIdle
	dw BagonAnimationIdle
	dw ShelgonAnimationIdle
	dw SalamenceAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw BeldumAnimationIdle
	dw MetangAnimationIdle
	dw MetagrossAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw GlaceonAnimationIdle
	dw LeafeonAnimationIdle
	dw SylveonAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw RegiceAnimationIdle
	dw RegirockAnimationIdle
	dw RegisteelAnimationIdle
	dw HeatranAnimationIdle
	dw ManaphyAnimationIdle
	dw JirachiAnimationIdle
	dw CelebiAnimationIdle
	dw DeoxysAnimationIdle
	dw MewAnimationIdle
	assert_table_length NUM_POKEMON
